In [2]:
import pandas as pd
import os

In [11]:
INITIAL_DATA_DIR = os.path.join(os.getcwd(), "initial_data")

In [47]:
def path(*kwargs):
    return os.path.join(*kwargs)

In [58]:
list_files = os.listdir(INITIAL_DATA_DIR)
l =[]
for file in list_files:
    if not l:
        l.append(pd.read_csv(path(INITIAL_DATA_DIR,file)))
    else:
        csv = pd.read_csv(path(INITIAL_DATA_DIR,file))
        df = pd.concat([l[-1],csv],axis=0)
        l.append(df)
        
        
df = l[-1]

In [62]:
df.sort_values(by="Report.Date",ascending=True,inplace=True)

In [64]:
df.head()

,Report.Date,Route,Time,Day,Location,Incident,Min.Delay,Min.Gap,Direction,Vehicle
6,2014-01-02,504,6:38:00 PM,Thursday,Roncesvalles and King Street West,Utilized Off Route,4.0,7.0,E/B,4100.0
0,2014-01-02,505,6:31:00 AM,Thursday,Dundas and Roncesvalles,Late Leaving Garage,4.0,8.0,E/B,4018.0
1,2014-01-02,504,12:43:00 PM,Thursday,King and Shaw,Utilized Off Route,20.0,22.0,E/B,4128.0
2,2014-01-02,501,2:01:00 PM,Thursday,Kingston road and Bingham,Held By,13.0,19.0,W/B,4016.0
3,2014-01-02,504,2:22:00 PM,Thursday,King St. and Roncesvalles Ave.,Investigation,7.0,11.0,W/B,4175.0

In [65]:
df.tail()

,Report.Date,Route,Time,Day,Location,Incident,Min.Delay,Min.Gap,Direction,Vehicle
10883,2025-10-31,510 SPADINA,15:04,Friday,SPADINA AND QUEEN,MISCELLANEOUS GENERAL STREETCAR DELAY,0.0,0.0,NaN,0
10884,2025-10-31,512 ST. CLAIR,15:47,Friday,ST CLAIR WEST STATION,INJURIED/ILL CUSTOMER â TRANSPORTED,6.0,12.0,NaN,4462
10885,2025-10-31,510 SPADINA,15:48,Friday,SPADINA STATION,UNABLE TO MAINT SCHED DUE TO TRAF/PASS CONGES,10.0,15.0,W,4612
10887,2025-10-31,510 SPADINA,16:09,Friday,SPADINA AND COLLEGE,DISORDERLY PATRON,5.0,10.0,N,4436
10869,2025-10-31,304 KING,03:46,Friday,DISTILLERY LOOP,INJURIED/ILL CUSTOMER â TRANSPORTED,47.0,57.0,NaN,4521